import { useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { AlertCircle, ArrowRight, Check, Clock3, Package, RefreshCcw, ShieldCheck, X } from 'lucide-react'
import { api, type Proposal, type Session } from '../../lib/api'
import { shortDate, titleCase } from '../../lib/format'
import { EmptyState, LoadingState, PageHeading, QueryBlock, StatusPill } from '../../components/ui'

export function ApprovalsView({ session }: { session: Session }) {
  const proposals = useQuery({ queryKey: ['proposals'], queryFn: api.proposals })
  const [filter, setFilter] = useState('all')
  const visible = useMemo(() => (proposals.data?.items || []).filter((item) => filter === 'all' || (filter === 'pending' ? item.status.toLowerCase() === 'pending_review' : item.status.toLowerCase() === filter)), [filter, proposals.data])
  const pending = (proposals.data?.items || []).filter((item) => item.status.toLowerCase() === 'pending_review').length
  const canReview = ['admin', 'operator'].includes(session.user.role)
  return <div className="content-page"><PageHeading eyebrow="HUMAN REVIEW" title="Review before action." description="Approve, edit, or reject service requests with the order and policy consequence in view." action={<div className="page-stats"><span><strong>{pending}</strong> awaiting review</span></div>} /><div className="operations-layout"><section className="operations-main"><div className="section-heading"><div><p className="eyebrow">ACTION QUEUE</p><h2>Return proposals</h2></div><button className="icon-button" type="button" onClick={() => void proposals.refetch()} title="Refresh proposals" aria-label="Refresh proposals"><RefreshCcw size={17} /></button></div><div className="filter-segments approvals-filter" role="group" aria-label="Filter proposals">{['all', 'pending', 'recorded', 'rejected', 'expired'].map((value) => <button key={value} className={filter === value ? 'active' : ''} type="button" aria-pressed={filter === value} onClick={() => setFilter(value)}>{titleCase(value)}</button>)}</div><QueryBlock title="Could not load action proposals" error={proposals.error} retry={() => void proposals.refetch()}>{proposals.isPending ? <LoadingState label="Loading review queue…" /> : visible.length === 0 ? <EmptyState icon={<ShieldCheck size={22} />} title={filter === 'all' ? 'No proposals yet' : `No ${filter} proposals`} description="Return requests that need a decision will be recorded here." /> : <div className="approval-list">{visible.map((proposal) => <ApprovalCard key={proposal.id} proposal={proposal} canReview={canReview} />)}</div>}</QueryBlock></section><aside className="operations-aside"><div className="guidance-card"><span className="guidance-icon"><ShieldCheck size={22} /></span><p className="eyebrow">DECISION POLICY</p><h3>Stay in control of service actions</h3><p>Each approval is bound to a specific proposal version. The server rechecks the order, access, and policy before recording a return.</p><div className="guidance-divider" /><div className="guidance-step"><span>01</span><p>Review the requested item, condition, and reason.</p></div><div className="guidance-step"><span>02</span><p>Edit the reason or reject if context is incomplete.</p></div><div className="guidance-step"><span>03</span><p>Approve once the proposed action is justified.</p></div></div></aside></div></div>
}

function ApprovalCard({ proposal, canReview }: { proposal: Proposal; canReview: boolean }) {
  const queryClient = useQueryClient()
  const [editing, setEditing] = useState(false)
  const [editedReason, setEditedReason] = useState(proposal.reason)
  const review = useMutation({
    mutationFn: (decision: 'approve' | 'edit' | 'reject') => api.reviewProposal(proposal.id, { decision, version: proposal.version, ...(decision === 'edit' ? { edited_reason: editedReason.trim() } : {}) }),
    onSuccess: () => { setEditing(false); void queryClient.invalidateQueries({ queryKey: ['proposals'] }); void queryClient.invalidateQueries({ queryKey: ['conversation', proposal.conversation_id] }) },
  })
  const pending = proposal.status.toLowerCase() === 'pending_review'
  return <article className="approval-card"><div className="approval-card-top"><span className="approval-symbol"><Package size={19} /></span><div><p className="eyebrow">RETURN REQUEST · {proposal.id}</p><h3>Order {proposal.order_id}</h3></div><StatusPill value={proposal.status} /></div><div className="approval-detail-grid"><div><span>Quantity</span><strong>{proposal.quantity}</strong></div><div><span>Item condition</span><strong>{titleCase(proposal.condition)}</strong></div><div><span>Proposal version</span><strong title={proposal.version}>{proposal.version.length > 12 ? `${proposal.version.slice(0, 8)}…` : proposal.version}</strong></div><div><span>Created</span><strong>{shortDate(proposal.created_at)}</strong></div></div><div className="proposal-reason"><span>CUSTOMER REASON</span><p>{proposal.reason}</p></div>{proposal.policy_result?.explanation && <div className="approval-exception"><AlertCircle size={17} /><div><strong>{titleCase(proposal.policy_result.code || 'Policy assessment')}</strong><p>{proposal.policy_result.explanation}</p></div></div>}{proposal.consequence && <p className="approval-consequence"><ArrowRight size={15} />{proposal.consequence}</p>}{proposal.return_record_id && <div className="inline-success"><Check size={15} /> Return record {proposal.return_record_id} was created.</div>}{pending && canReview && <div className="approval-controls">{editing ? <div className="edit-reason"><label htmlFor={`edit-${proposal.id}`}>Edited reason</label><textarea id={`edit-${proposal.id}`} rows={3} value={editedReason} onChange={(event) => setEditedReason(event.target.value)} /><div><button className="btn btn-secondary" type="button" onClick={() => setEditing(false)}>Cancel</button><button className="btn btn-primary" type="button" disabled={!editedReason.trim() || review.isPending} onClick={() => review.mutate('edit')}>Save edit</button></div></div> : <><button className="btn btn-secondary" type="button" disabled={review.isPending} onClick={() => review.mutate('reject')}><X size={15} /> Reject</button><button className="btn btn-secondary" type="button" disabled={review.isPending} onClick={() => setEditing(true)}>Edit reason</button><button className="btn btn-primary" type="button" disabled={review.isPending} onClick={() => review.mutate('approve')}><Check size={15} /> Approve</button></>}{review.isPending && <span className="mutating-note"><Clock3 size={14} /> Recording decision…</span>}{review.isError && <p className="inline-error" role="alert">{review.error.message} <button type="button" onClick={() => void queryClient.invalidateQueries({ queryKey: ['proposals'] })}>Refresh version</button></p>}</div>}{pending && !canReview && <p className="permission-note"><ShieldCheck size={15} /> Operator or admin access is required to review.</p>}</article>
}
