"""document_authority

Revision ID: 8a76523eac61
Revises: 35088941d197
Create Date: 2026-09-27 15:49:26.022108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a76523eac61'
down_revision: Union[str, Sequence[str], None] = '35088941d197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authority', sa.String(length=30), nullable=False, server_default='uploaded'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('authority')

    # ### end Alembic commands ###
