"""workspace_return_policy_and_promised_delivery

Revision ID: b6e948c03bb6
Revises: 97abb4ff451f
Create Date: 2026-09-27 15:39:46.203507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6e948c03bb6'
down_revision: Union[str, Sequence[str], None] = '97abb4ff451f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('promised_delivery_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('return_policy', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_column('return_policy')

    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_column('promised_delivery_at')

    # ### end Alembic commands ###
