"""guest_verification_challenges

Revision ID: cf03ccb11945
Revises: 8a76523eac61
Create Date: 2026-09-27 15:51:29.084123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf03ccb11945'
down_revision: Union[str, Sequence[str], None] = '8a76523eac61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_challenges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guest_challenges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guest_challenges_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guest_challenges_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guest_challenges_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_guest_challenges_order_id'))

    op.drop_table('guest_challenges')
    # ### end Alembic commands ###
